version: '3'
services:
    pose-detection-humble:
        privileged: true
        image: "olagh/pose_detection:latest"
        network_mode: host
        environment:
            - PULSE_SERVER=tcp:host.docker.internal:4713
            - ROS_MASTER_URI=$ROS_MASTER_URI
            - ROS_IP=$ROS_IP
            - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
            - DISPLAY=$DISPLAY
            - FASTRTPS_DEFAULT_PROFILES_FILE=/profile/fastrtps_default_profiles.xml
        volumes:
            - /tmp/.X11-unix/:/tmp/.X11-unix/
            - ./profile:/profile
            #- ./smart_home_launch.bash:/tmp/smart_home_launch.bash 
            - /dev/video2:/dev/video0
        tty: true
        #command: /tmp/smart_home_launch.bash 
        # access to 1 GPU device
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: [gpu]


